name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Determine the environment based on the branch
            if [ "${{ github.ref_name }}" == "main" ]; then
              ENV_PORT=5173
              ENV_NAME="main"
            elif [ "${{ github.ref_name }}" == "dev" ]; then
              ENV_PORT=5174
              ENV_NAME="dev"
            elif [ "${{ github.ref_name }}" == "test" ]; then
              ENV_PORT=5175
              ENV_NAME="test"
            elif [ "${{ github.ref_name }}" == "staging" ]; then
              ENV_PORT=5176
              ENV_NAME="staging"
            else
              echo "Unknown branch. Skipping deployment."
              exit 1
            fi

            echo "Deploying branch $ENV_NAME on port $ENV_PORT"

            # Navigate to the project directory
            cd /home/ubuntu/multi-branch-react || exit 1

            # Pull the latest changes
            git reset --hard
            git clean -fd
            git pull origin ${{ github.ref_name }}

            # Install dependencies and build the app
            npm install

            # Restart the environment using PM2
            pm2 delete $ENV_NAME || true
            pm2 start "npm run dev -- --port $ENV_PORT --host 0.0.0.0" --name $ENV_NAME
            pm2 save
