name: Deploy React App

on:
  push:
    branches:
      - main
      - dev
      - test
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 100.27.224.83
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/multi-branch-react
            git fetch
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            npm install
            npm run build
            pm2 delete ${{ github.ref_name }} || true
            pm2 start npm --name ${{ github.ref_name }} -- start --prefix build
